export const APP_NAME = 'Dyqani Optik'

export const NAV = {
  dashboard: 'Paneli',
  klientet: 'Klientët',
  kategorite: 'Kategoritë',
  produktet: 'Produktet',
  inventari: 'Inventari',
  porosite: 'Porositë',
  pagesat: 'Pagesat',
  recetat: 'Recetat',
  rezervimet: 'Rezervimet',
  garancite: 'Garancitë',
  njoftimet: 'Njoftimet',
  dergesat: 'Dërgesat',
  kontrolletSyve: 'Kontrollet e Syve',
  historikuVizitave: 'Historiku i Vizitave',
  lentet: 'Lentet',
  punonjesit: 'Punonjësit',
  furnitoret: 'Furnitorët',
}

export const ACTIONS = {
  new: 'Shto të ri',
  edit: 'Ndrysho',
  delete: 'Fshi',
  save: 'Ruaj',
  cancel: 'Anulo',
  back: 'Kthehu',
  view: 'Shiko',
  viewDetails: 'Shiko detajet',
  details: 'Detajet',
  search: 'Kërko',
  track: 'Ndiq',
  close: 'Mbyll',
  previous: 'Mbrapa',
  next: 'Para',
  logout: 'Dil',
  login: 'Hyr',
  register: 'Regjistrohu',
  refresh: 'Rifresko',
  confirmDelete: 'A jeni i sigurt që doni ta fshini këtë regjistrim?',
  addItem: 'Shto artikull',
  saving: 'Duke u ruajtur…',
  markAsRead: 'Shëno si të lexuar',
  markAsUnread: 'Shëno si të palexuar',
  viewAllNotifications: 'Shiko të gjitha njoftimet',
  saveProduct: 'Ruaj produktin',
  saveCategory: 'Ruaj kategorinë',
  saveInventory: 'Ruaj inventarin',
}

export const MESSAGES = {
  loadError: 'Ngarkimi i të dhënave dështoi. Provoni përsëri.',
  saveError: 'Ruajtja dështoi. Kontrolloni fushat dhe provoni përsëri.',
  saveSuccess: 'U ruajt me sukses.',
  deleteSuccess: 'U fshi me sukses.',
  deleteError: 'Fshirja dështoi.',
  loginError: 'Hyrja dështoi. Kontrolloni kredencialet.',
  networkError: 'Gabim rrjeti. Kontrolloni lidhjen.',
  required: 'Kjo fushë është e detyrueshme.',
  loading: 'Duke u ngarkuar…',
  noRecords: 'Nuk u gjet asnjë regjistrim.',
  noBrandModel: 'Pa markë/model',
  noEmail: 'Pa email',
  noNotes: 'Nuk ka shënime.',
  noDescription: 'Pa përshkrim',
  noNotifications: 'Nuk ka njoftime ende.',
  noMeasurementDetails: 'Pa detaje matjeje',
  unknown: 'E panjohur',
  unlinked: 'Pa lidhje',
  unassigned: 'Pa caktuar',
  uncategorized: 'Pa kategori',
  unknownItem: 'Artikull i panjohur',
  unknownBrand: 'Markë e panjohur',
  imagePreviewNote: 'Parapamje e imazhit; ruajtja në server nuk është konfiguruar ende.',
  stockAdjustHint: 'Përdorni vlera pozitive ose negative për të rregulluar stokun.',
  filterProductLensInSearch: 'Filtro sipas produktit / lentes në kërkim',
}

export const ORDER_STATUS = {
  neProces: 'Ne proces',
  perfunduar: 'E perfunduar',
  anuluar: 'Anuluar',
}

export const FILTERS = {
  itemsPerPage: 'Artikuj për faqe',
  pageSize: 'Madhësia e faqes',
  perPage: (size) => `${size} për faqe`,
  searchCustomers: 'Kërko sipas emrit, email-it ose telefonit',
  searchOrders: 'Kërko porosi',
  searchOrdersPlaceholder: 'Nr. porosie, klient ose email',
  searchProducts: 'Kërko produkte',
  searchProductsPlaceholder: 'Kërko sipas emrit, markës ose modelit',
  searchEmployees: 'Kërko sipas emrit, email-it ose telefonit',
  searchPayments: 'Kërko sipas porosisë, klientit ose ID',
  searchCategories: 'Kërko kategori',
  searchInventory: 'Kërko inventar',
  searchInventoryPlaceholder: 'Kërko sipas produktit, markës ose materialit',
  searchPrescriptions: 'Kërko sipas #, klientit ose mjekut',
  searchCheckups: 'Kërko sipas pacientit, punonjësit, recetës',
  searchReservations: 'Kërko rezervime',
  searchReservationsPlaceholder: 'Nr. rezervimi, klient, status',
  searchNotifications: 'Kërko njoftime',
  searchNotificationsPlaceholder: 'Mesazh, klient, porosi',
  searchWarranties: 'Kërko garanci',
  searchWarrantiesPlaceholder: 'Klient, porosi, artikull, kushte',
  searchDeliveries: 'Kërko dërgesa',
  searchDeliveriesPlaceholder: 'Nr. porosie, klient, tracking',
  searchLenses: 'Kërko lente',
  searchLensesPlaceholder: 'Lloji, prodhuesi ose SKU',
  searchLensesType: 'Filtro sipas llojit',
  searchSuppliers: 'Kërko sipas kompanisë ose kontaktit',
  allStatuses: 'Të gjitha statuset',
  allRoles: 'Të gjitha rolet',
  allCategories: 'Të gjitha kategoritë',
  allEmployees: 'Të gjithë punonjësit',
  allCustomers: 'Të gjithë klientët',
  allOrders: 'Të gjitha porositë',
  status: 'Statusi',
  role: 'Roli',
  category: 'Kategoria',
  customer: 'Klienti',
  employee: 'Punonjësi',
  order: 'Porosia',
  stockStatus: 'Statusi i stokut',
  lowStock: 'Stok i ulët',
  healthyStock: 'Stok i mirë',
  reservationDate: 'Data e rezervimit',
  createdDate: 'Data e krijimit',
  expiration: 'Skadimi',
  shipDate: 'Data e nisjes',
  productLens: 'Produkti / lente',
  unread: 'E palexuar',
  read: 'E lexuar',
  unreadCount: (n) => `${n} të palexuara`,
  warrantyActive: 'Aktive',
  warrantyExpiring: 'Skadon së shpejti',
  warrantyExpired: 'Skaduar',
}

export const TABLE = {
  number: '#',
  actions: 'Veprimet',
  order: 'Porosia',
  customer: 'Klienti',
  total: 'Totali',
  status: 'Statusi',
  ordered: 'Porositur',
  name: 'Emri',
  role: 'Roli',
  email: 'Email',
  phone: 'Telefoni',
  amount: 'Shuma',
  method: 'Metoda',
  date: 'Data',
  product: 'Produkti',
  category: 'Kategoria',
  price: 'Çmimi',
  stock: 'Stoku',
  current: 'Aktual',
  minimum: 'Minimumi',
  updated: 'Përditësuar',
  description: 'Përshkrimi',
  doctor: 'Mjeku',
  patient: 'Pacienti',
  employee: 'Punonjësi',
  prescription: 'Receta',
  notes: 'Shënimet',
  reservation: 'Rezervimi',
  schedule: 'Orari',
  message: 'Mesazhi',
  created: 'Krijuar',
  warranty: 'Garancia',
  productLens: 'Produkti / lente',
  expires: 'Skadon',
  delivery: 'Dërgesa',
  company: 'Kompania',
  contact: 'Kontakti',
  products: 'Produktet',
  type: 'Lloji',
  producer: 'Prodhuesi',
  index: 'Indeksi',
  coating: 'Veshja',
  lens: 'Lente',
}

export const FIELDS = {
  productName: 'Emri i produktit',
  category: 'Kategoria',
  selectCategory: 'Zgjidhni kategorinë',
  brand: 'Marka',
  model: 'Modeli',
  color: 'Ngjyra',
  price: 'Çmimi (€)',
  stock: 'Stoku',
  material: 'Materiali',
  productImage: 'Imazhi i produktit',
  activeProduct: 'Produkt aktiv',
  preview: 'Parapamje',
  categoryName: 'Emri',
  categoryDescription: 'Përshkrimi',
  activeCategory: 'Kategori aktive',
  product: 'Produkti',
  chooseProduct: 'Zgjidhni produktin',
  minimumStock: 'Stoku minimal',
  currentStock: 'Stoku aktual',
  adjustStock: 'Rregullo stokun',
  afterAdjustment: 'Pas rregullimit',
  inventoryItem: 'Artikull inventari',
}

export const STATUS_LABELS = {
  active: 'Aktiv',
  inactive: 'Joaktiv',
  pending: 'Në pritje',
  lowStock: 'Stok i ulët',
  healthy: 'Stok i mirë',
  inStock: (n) => `${n} në stok`,
}

export const ROLES = {
  admin: 'Administrator',
  employee: 'Punonjës',
  user: 'Përdorues',
}

export const PAYMENT_STATUS = {
  completed: 'E përfunduar',
  inProcess: 'Ne proces',
}

export const NOTIFICATIONS = {
  title: 'Njoftimet',
  menuLabel: 'Menyja e njoftimeve',
}

export const DASHBOARD = {
  recentOrders: 'Porositë e fundit',
  recentOrdersSubtitle: 'Aktiviteti i fundit nga porositë.',
  orderStatusTitle: 'Statusi i porosive',
  orderStatusSubtitle: 'Shpërndarja sipas statusit.',
  revenueTitle: 'Tendenca e të ardhurave',
  revenueSubtitle: 'Totali i porosive sipas datës.',
  ordersTooltip: 'porosi',
  inventoryAlerts: 'Alarme inventari',
  stockThreshold: 'sasiaAktuale ≤ sasiaMinimale',
  alertsCount: (n) => `${n} alarme`,
  noStockAlerts: 'Nuk ka alarme stoku.',
  currentQty: 'Sasia aktuale',
  minQty: 'Sasia minimale',
}

export const VALIDATION = {
  productNameRequired: 'Emri i produktit është i detyrueshëm',
  selectCategory: 'Zgjidhni një kategori',
  priceRequired: 'Çmimi është i detyrueshëm',
  pricePositive: 'Çmimi duhet të jetë pozitiv',
  stockRequired: 'Stoku është i detyrueshëm',
  stockNonNegative: 'Stoku nuk mund të jetë negativ',
  categoryNameRequired: 'Emri i kategorisë është i detyrueshëm',
  descriptionMax: 'Përshkrimi nuk mund të kalojë 220 karaktere',
  selectProduct: 'Zgjidhni një produkt',
  minimumStockRequired: 'Stoku minimal është i detyrueshëm',
  minZeroOrHigher: 'Duhet të jetë 0 ose më shumë',
  currentStockRequired: 'Stoku aktual është i detyrueshëm',
}

export const PAGE_TITLES = {
  orders: { title: 'Menaxhimi i porosive', description: 'Shikoni porositë, përditësoni statusin dhe menaxhoni detajet.' },
  products: { title: 'Katalogu i produkteve', description: 'Menaxhoni inventarin, filtroni sipas kategorisë dhe mbajeni katalogun në sync.' },
  employees: { title: 'Menaxhimi i punonjësve', description: 'Menaxhoni profilet, rolet dhe statusin aktiv të punonjësve.' },
  payments: { title: 'Menaxhimi i pagesave', description: 'Regjistroni pagesa, shikoni historikun dhe menaxhoni statuset.' },
  categories: { title: 'Menaxhimi i kategorive', description: 'Organizoni produktet në kategori të qarta.' },
  inventory: { title: 'Menaxhimi i inventarit', description: 'Ndiqni sasitë, lokacionet dhe alarmet e stokut.' },
  prescriptions: { title: 'Menaxhimi i recetave', description: 'Regjistroni dhe menaxhoni recetat e syve të klientëve.' },
  checkups: { title: 'Kontrollet e syve', description: 'Regjistroni dhe menaxhoni kontrollet e syve.' },
  reservations: { title: 'Menaxhimi i rezervimeve', description: 'Planifikoni dhe menaxhoni rezervimet e klientëve.' },
  notifications: { title: 'Menaxhimi i njoftimeve', description: 'Dërgoni dhe menaxhoni njoftimet për klientët.' },
  warranties: { title: 'Menaxhimi i garancive', description: 'Ndiqni garancitë e produkteve dhe lenteve.' },
  deliveries: { title: 'Menaxhimi i dërgesave', description: 'Planifikoni dhe ndiqni dërgesat e porosive.' },
  lenses: { title: 'Menaxhimi i lenteve', description: 'Menaxhoni lente kontakti dhe recetat e lidhura.' },
  suppliers: { title: 'Menaxhimi i furnitorëve', description: 'Menaxhoni furnitorët dhe produktet e furnizuara.' },
}

export const pageLabel = (current, total) => `Faqja ${current} / ${total}`

export const FIELD = {
  customer: 'Klienti',
  order: 'Porosia',
  item: 'Artikulli',
  status: 'Statusi',
  employee: 'Punonjësi',
  product: 'Produkti',
  category: 'Kategoria',
  price: 'Çmimi',
  stock: 'Stoku',
  brand: 'Marka',
  model: 'Modeli',
  color: 'Ngjyra',
  material: 'Materiali',
  email: 'Email',
  phone: 'Telefoni',
  address: 'Adresa',
  birthDate: 'Data e lindjes',
  createdOn: 'Regjistruar më',
  name: 'Emri',
  description: 'Përshkrimi',
  prescription: 'Receta',
  deliveryDate: 'Data e dorëzimit',
  orderDate: 'Data e porosisë',
  orderStatus: 'Statusi i porosisë',
  items: 'Artikujt',
  qty: 'Sasia',
  total: 'Totali',
  action: 'Veprimi',
  subtotal: 'Nëntotali',
  taxEstimate: 'Vlerësim i taksës',
  summary: 'Përmbledhje',
  message: 'Mesazhi',
  created: 'Krijuar',
  carrier: 'Kompania transportuese',
  trackingNumber: 'Numri i gjurmimit',
  deliveryAddress: 'Adresa e dërgesës',
  shipDate: 'Data e nisjes',
  arrivalDate: 'Data e mbërritjes',
  currentStock: 'Stoku aktual',
  minimumThreshold: 'Pragu minimal',
  updatedOn: 'Përditësuar më',
  contact: 'Kontakti',
  employeeId: 'ID e punonjësit',
  notes: 'Shënime',
  date: 'Data',
  time: 'Ora',
  startDate: 'Data e fillimit',
  expiration: 'Skadimi',
  recordId: 'ID e regjistrimit',
  overview: 'Përmbledhje',
  specifications: 'Specifikimet',
  contactDetails: 'Të dhënat e kontaktit',
  profileDetails: 'Të dhënat e profilit',
  stockDetails: 'Detajet e stokut',
  productReference: 'Referenca e produktit',
  orderMetadata: 'Metadatat e porosisë',
  coverageDetails: 'Detajet e mbulimit',
  shipmentOverview: 'Përmbledhja e dërgesës',
  paymentHistory: 'Historiku i pagesave',
  patientOverview: 'Përmbledhja e pacientit',
  measurementNotes: 'Shënimet e matjeve',
  recommendations: 'Rekomandimet',
  patientHistory: 'Historiku i pacientit',
  reservationOverview: 'Përmbledhja e rezervimit',
  customerHistory: 'Historiku i klientit',
  editProfile: 'Ndrysho profilin',
}

export const STATUS = {
  active: 'Aktiv',
  inactive: 'Joaktiv',
  expired: 'Skaduar',
  expiringSoon: 'Skadon së shpejti',
  lowStock: 'Stok i ulët',
  healthyStock: 'Stok i mirë',
  pending: 'Në pritje',
  notAssigned: 'Pa caktuar',
  uncategorized: 'Pa kategori',
  noPrescription: 'Pa recetë të zgjedhur',
  noDescription: 'Nuk ka përshkrim.',
  noTerms: 'Nuk ka kushte garancie.',
  noPatient: 'Pa pacient të lidhur.',
  noEmployee: 'Pa punonjës të lidhur.',
  noDetails: 'Nuk ka detaje.',
  noAdditionalNotes: 'Nuk ka shënime shtesë.',
  noPreviousCheckups: 'Nuk ka kontrolle të mëparshme për këtë pacient.',
  noPreviousReservations: 'Nuk ka rezervime të mëparshme për këtë klient.',
  lensItem: 'Artikull lente',
  units: 'njësi',
}

export const DETAIL = {
  notFound: 'Regjistrimi nuk u gjet.',
  addAtLeastOneItem: 'Shtoni të paktën një artikull para ruajtjes.',
  noLineItems: 'Nuk ka artikuj. Shtoni një produkt për të filluar porosinë.',
  changeProduct: 'Ndrysho produktin',
  selectProduct: 'Zgjidh produktin',
  remove: 'Hiq',
  markAsRead: 'Shëno si të lexuar',
  markAsUnread: 'Shëno si të palexuar',
  cancelReservation: 'Anulo rezervimin',
  editWarranty: 'Ndrysho garancinë',
}
