# Emri i projektit
spring.application.name=backend

# Lidhja me Databazen (localhost punon per te gjithe)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DyqaniOptikesDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sdiqapobahet72
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.security.user.name=admin
spring.security.user.password=12345

# Magjia që krijon tabelat automatikisht
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.security.enabled=false