# Emri i projektit
spring.application.name=backend

# 1. Lidhja me Databazen (Connection String)
# localhost:1433 eshte adresa dhe porti i SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DyqaniOptikesDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sdiqapobahet72

# 2. Hibernate Settings
# 'update' do te thote qe Java do t'i krijoje automatikisht tabelat ne SQL
spring.jpa.hibernate.ddl-auto=update
# 'show-sql=true' na lejone te shohim ne console queries qe ekzekutohen
spring.jpa.show-sql=true

# 3. Dialect
# I tregon Spring-ut qe jemi duke perdorur MSSQL dhe jo MySQL ose Oracle
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# 4. Date Formatting
# Siguron qe datat te jene ne formatin "2026-04-05" dhe jo si numra te gjate
spring.jackson.serialization.write-dates-as-timestamps=false